Repository AY2223S2-CS2113-W13-3/tp, pull requests merged in 2023-03, with the labels that each got.

#23 Branch add command
  CONTRIBUTORS.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/CommandResult.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/IncorrectCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/general/Parser.java
  src/main/java/seedu/duke/general/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#33 add ListCommand feature
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/general/Parser.java
  src/main/java/seedu/duke/general/Ui.java
Labels: type.Epic, type.Task, priority.High

#35 Add JUnit Test
  src/test/java/seedu/duke/commands/AddCommandTest.java
Labels: type.Task

#40 Add find command feature
  src/main/java/seedu/duke/commands/FindCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/general/Parser.java
Labels: type.Epic, type.Task, priority.High

#45 FindCommand test
  src/test/java/seedu/duke/commands/FindCommandTest.java
Labels: type.Enhancement, priority.Medium

#51 Improve user interface for help message display
  src/main/java/seedu/duke/commands/HelpCommand.java
Labels: priority.Low, severity.VeryLow

#52 Branch assertion
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/commands/RemoveCommand.java
  src/main/java/seedu/duke/general/Parser.java
  src/main/java/seedu/duke/general/Ui.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
Labels: priority.High

#58 Logging
  src/main/java/seedu/duke/Duke.java
Labels: priority.Low

#66 Add quantity attribute in Food Class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/general/Parser.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
Labels: type.Epic, priority.High

#73 Update Add feature in UserGuide
  docs/UserGuide.md
Labels: priority.High

#89 Add method to check date
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Unit.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/food/Unit.java
  src/main/java/seedu/duke/general/Parser.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
Labels: type.Bug, severity.Medium

#94 Add category attribute and update AddCommandTest
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodCategory.java
  src/main/java/seedu/duke/general/Parser.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
Labels: priority.Medium

#93 Update Command
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/RemoveCommand.java
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/general/Parser.java
  src/main/java/seedu/duke/utils/DateFormatter.java
Labels: type.Story, priority.High

#97 add category to find and update commands
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
Labels: type.Story, priority.High

#95 Added storage support for attribute 'category'
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/storage/FoodListDecoder.java
  src/main/java/seedu/duke/storage/FoodListEncoder.java
  src/main/java/seedu/duke/storage/StorageFile.java
  src/test/java/seedu/duke/storage/FoodListEncoderTest.java
Labels: priority.High, priority.Medium
