Repository AY2223S2-CS2113-W13-3/tp, pull requests merged in 2023-04, with the labels that each got.

#106 Update proper AddCommand format
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/general/Parser.java
  src/test/java/seedu/duke/storage/FoodListEncoderTest.java
Labels: type.Enhancement, priority.Medium

#166 sort the food list in order of the expiry dates (from expiring soon t…
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
Labels: type.Task, priority.High

#170 Update quantity bug
  src/main/java/seedu/duke/commands/FindCommand.java
  src/main/java/seedu/duke/commands/UpdateCommand.java
Labels: priority.Medium

#171 Update quantity bug addition
  src/main/java/seedu/duke/commands/UpdateCommand.java
Labels: priority.High

#172 better validation for update flags
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/exceptions/InvalidFlagException.java
Labels: priority.High

#173 improve index validation for update command
  src/main/java/seedu/duke/commands/UpdateCommand.java
Labels: priority.High

#176 Fix/date parsing
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/ListCommand.java
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/storage/FoodListDecoder.java
  src/main/java/seedu/duke/utils/DateFormatter.java
  src/main/java/seedu/duke/utils/Validator.java
  src/test/java/seedu/duke/commands/FindCommandTest.java
  src/test/java/seedu/duke/commands/RemoveCommandTest.java
  src/test/java/seedu/duke/storage/FoodListEncoderTest.java
Labels: priority.Medium

#193 Update find commands improvements
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/FindCommand.java
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/exceptions/InvalidFlagValueException.java
  src/main/java/seedu/duke/food/Food.java
  src/main/java/seedu/duke/food/FoodList.java
  src/main/java/seedu/duke/utils/DateFormatter.java
  src/main/java/seedu/duke/utils/Validator.java
  src/test/java/seedu/duke/commands/FindCommandTest.java
Labels: priority.Medium

#211 change error message
  src/main/java/seedu/duke/commands/FindCommand.java
Labels: priority.Medium

#212 Fix: flag handling for multi word flag values
  src/main/java/seedu/duke/commands/FindCommand.java
  src/main/java/seedu/duke/commands/UpdateCommand.java
Labels: type.Bug, priority.High

#217 better handling of quantity-unit dependence
  src/main/java/seedu/duke/commands/UpdateCommand.java
  src/main/java/seedu/duke/food/Food.java
Labels: type.Enhancement, priority.Medium

#221 handle exception thrown by scanner
  src/main/java/seedu/duke/Duke.java
Labels: priority.Medium

#227 add more tests for find & update commands
  src/test/java/seedu/duke/commands/FindCommandTest.java
  src/test/java/seedu/duke/commands/UpdateCommandTest.java
Labels: priority.Medium

#228 fix checking process for quantity flag when unit should be updated
  src/main/java/seedu/duke/commands/UpdateCommand.java
Labels: priority.High

#229 update UG for find and update commands
  docs/UserGuide.md
Labels: priority.High

#236 update DG with find and update commands
  docs/DeveloperGuide.md
  docs/images/FindCommandClassDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/UpdateCommandClassDiagram.png
  docs/images/UpdateCommandSequenceDiagram.png
  docs/puml/FindCommandClassDiagram.puml
  docs/puml/FindCommandSequenceDiagram.puml
  docs/puml/UpdateCommandClassDiagram.puml
  docs/puml/UpdateCommandSequenceDiagram.puml
  docs/team/davidvin357.md
  src/main/java/seedu/duke/commands/UpdateCommand.java
Labels: priority.High

#246 minor update to dg & ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Low

#248 fix category, unit, quantity validation issues
  src/main/java/seedu/duke/storage/FoodListDecoder.java
Labels: priority.High
